# 仮でベースラインを決定する
baseline = ["A", "G#m(b5)", "A", "F#m"]
# 各キーに対するコード
c = ['C', 'E', 'G']
d = ['D', 'F#', 'A']
e = ['E', 'G#', 'B']
f = ['F', 'A', 'C']
g = ['G', 'B', 'D']
a = ['A', 'C#', 'E']
b = ['B', 'D#', 'F#']
cm = ['C', 'Eb', 'G']
dm = ['D', 'F', 'A']
em = ['E', 'G', 'B']
fm = ['F', 'Ab', 'C']
gm = ['G', 'Bb', 'D']
am = ['A', 'C', 'E']
bm = ['B', 'D', 'F#'] 
csharp = ['C#', 'F', 'G#']
dsharp = ['D#', 'G', 'A#']
fsharp = ['F#', 'A#', 'G#']
gsharp = ['G#', 'C', 'D#']
asharp = ['A#', 'D', 'F']
